name: build-fotd-config-files

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  push-json:
    runs-on: ubuntu-latest
    steps:
      # Checkout current branch
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      # Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Switch to release branch (or create it)
      - name: Prepare release branch
        run: |
          # Determine the branch/folder name safely
          if [ -n "$GITHUB_HEAD_REF" ]; then
          # PR event: source branch
          CURRENT_BRANCH="$GITHUB_HEAD_REF"
          FILE_NAME="${GITHUB_REF#refs/pull/}"   # PR number
          else
          # Push or workflow_dispatch
          CURRENT_BRANCH="${GITHUB_REF##*/}"
          FILE_NAME="$CURRENT_BRANCH"
          fi

          echo "Using branch: $CURRENT_BRANCH"
          echo "File name/folder: $FILE_NAME"

          # Fetch and checkout release branch
          git fetch origin release || echo "Release branch does not exist"
          git checkout release || git checkout -b release
  
          # Copy files from the source branch (CURRENT_BRANCH)
          git checkout "$CURRENT_BRANCH" -- fotd/app-config.json
          git checkout "$CURRENT_BRANCH" -- fotd/facts-list.json

          # Create folders for new version
          mkdir -p fotd/app-config
          mkdir -p fotd/facts-list
          mv fotd/app-config.json fotd/app-config/"$FILE_NAME".json
          mv fotd/facts-list.json fotd/facts-list/"$FILE_NAME".json

      - name: Commit & push
        run: |
          git add fotd/app-config/"$FILE_NAME".json
          git add fotd/facts-list/"$FILE_NAME".json
          git commit -m "Add versioned fotd JSON files" || echo "No changes to commit"
          git push origin release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}