name: build-fotd-config-files

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  push-json:
    runs-on: ubuntu-latest
    steps:
      # Checkout current branch
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Switch to release branch (or create it)
      - name: Prepare release branch
        run: |
          # Get current branch name
          CURRENT_BRANCH="${{ github.ref_name }}"
          echo "Current branch: $CURRENT_BRANCH"
      
          # Fetch and checkout release branch (create if missing)
          git fetch origin release || echo "Release branch does not exist"
          git checkout release || git checkout -b release

          # Copy files from main branch
          git checkout "$CURRENT_BRANCH" -- fotd/app-config.json
          git checkout "$CURRENT_BRANCH" -- fotd/facts-list.json

          # Create folders for new version
          mkdir -p fotd/app-config
          mkdir -p fotd/facts-list
          mv fotd/app-config.json fotd/app-config/"$CURRENT_BRANCH".json
          mv fotd/facts-list.json fotd/facts-list/"$CURRENT_BRANCH".json

      - name: Commit & push
        run: |
          git add fotd/app-config/"$CURRENT_BRANCH".json
          git add fotd/facts-list/"$CURRENT_BRANCH".json
          git commit -m "Add "$CURRENT_BRANCH" of fotd JSON files" || echo "No changes to commit"
          git push origin release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}