name: update-login-json

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write


jobs:
  push-json:
    runs-on: ubuntu-latest
    steps:
      # Checkout current branch
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Switch to release branch (or create it)
      - name: Prepare release branch
        run: |
          git fetch origin release || echo "Release branch does not exist"
          git checkout release || git checkout -b release
          
          # Clean branch completely
          git rm -rf .
          git clean -fdx
          
          # Copy files from main branch
          git checkout main -- fotd/app-config.json
          git checkout main -- fotd/facts-list.json
    
          # Now copy files and create folders
          mkdir -p fotd/app-config
          mkdir -p fotd/facts-list
          mv fotd/app-config.json fotd/app-config/v2.json
          mv fotd/facts-list.json fotd/facts-list/v2.json

      # Commit and push changes
      - name: Commit & push
        run: |
          git add fotd/app-config/v1.json
          git add fotd/facts-list/v1.json
          git commit -m "Update login.json from workflow" || echo "No changes to commit"
          git push origin release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}