name: update-login-json

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write


jobs:
  push-json:
    runs-on: ubuntu-latest
    steps:
      # Checkout current branch
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Checkout release branch (create if missing)
      - name: Checkout release branch
        run: |
          git fetch origin release || echo "Release branch does not exist"
          git checkout release || git checkout -b release

      # Copy only the JSON file from current branch
      - name: Copy login.json
        run: |
          mkdir -p sample
          cp sample_1/login.json sample/login.json

      # Commit and push changes
      - name: Commit & push
        run: |
          git add sample/login.json
          git commit -m "Update login.json from workflow" || echo "No changes to commit"
          git push origin release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}