name: update-login-json

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  push-json:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Switch to release branch (create if missing)
      - name: Prepare release branch
        run: |
          git checkout --orphan release
          git rm -rf .  # remove all files
          mkdir -p sample
          cp sample/login.json sample/login.json  # copy your JSON
          git add sample/login.json
          git commit -m "Update login.json from workflow"
          git push origin release --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}