name: upload-config-files
on:
  pull_request:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      # Checkout current repo
      - uses: actions/checkout@v4

      # Upload file to release (creates release if missing)
      - name: Upload login.json to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: sample/login.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}